authentication strategy & option types
octokit/core.js pull request #32
Opened 2020-01-20 01:11 UTC by gr2m

2020-01-20 19:45 UTC, gr2m commented
It does not look like this is possible right now: https://stackoverflow.com/q/59828577/206879

2020-02-09 23:49 UTC, gr2m commented
I think we found a winner: https://github.com/octokit/rest.js/issues/1562#issuecomment-582678977

2020-07-17 03:06 UTC, EMONIII-cloud commented
P u

2020-09-17 03:48 UTC, atlslscsrv-app approved these changes

2020-09-23 09:41 UTC, reza86maker approved these changes

2020-09-23 09:45 UTC, reza86maker approved these changes

2020-10-02 16:06 UTC, watcher699 approved these changes

2020-11-22 10:09 UTC, prof-Shiva420 requested changes
# @ # @gimenete

2020-12-22 06:08 UTC, angelface79 approved these changes

2021-01-04 03:11 UTC, nnnwewe approved these changes

2021-01-05 00:52 UTC, dstiers11 approved these changes

2021-01-23 05:12 UTC, Bellybutn278 reviewed
This is indeed interesting, can someone explain this a bit better? Good neasure

2021-03-08 20:05 UTC, cabe73 approved these changes

2021-03-16 02:54 UTC, feartDev approved these changes
Approve..

2021-04-22 20:17 UTC, closed without merging